title: GreenAiriva
email: info@greenairiva.com.tr
description: >-
  GreenAiriva is a modular, energy-positive urban unit that selectively captures N₂O and high-GWP greenhouse gases at street level — with verified, auditable mass-based MRV data. Built for municipalities, industrial zones, and telecom operators.
baseurl: "" # GitHub Pages için
url: "https://www.greenairiva.com.tr"
twitter_username: greenairiva
github_username: greenairiva

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Bu dosyaları build’e dahil et
include:
  - career/jobs.json
  - career/tr/jobs.json
  - career/jobs        # İngilizce ilan .md dosyaları
  - career/tr/jobs     # Türkçe ilan .md dosyaları